name: Docker
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@v3.3.0  
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Docker Image Build naming-server
        working-directory: ./naming-server
        run: docker build -t naming-server:0.0.1-SNAPSHOT .

      - name: Docker Hub Push naming-server
        run: |
          docker tag naming-server:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/naming-server:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/naming-server:latest
          
      - name: Docker Image Build api-gateway
        working-directory: ./api-gateway
        run: docker build -t api-gateway:0.0.1-SNAPSHOT .
      
      - name: Docker Hub Push api-gateway
        run: |
          docker tag api-gateway:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest

      - name: Docker Image Build email-service
        working-directory: ./email-service
        run: docker build -t email-service:0.0.1-SNAPSHOT .
      
      - name: Docker Hub Push email-service 
        run: |
          docker tag email-service:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/email-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/email-service:latest

      - name: Docker Image Build user-service
        working-directory: ./user-service
        run: docker build -t user-service:0.0.1-SNAPSHOT .
      
      - name: Docker Hub Push user-service
        run: |
          docker tag user-service:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/user-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/user-service:latest
          
          
        
